source 'https://rubygems.org'
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'github-markup'
gem 'redcarpet'
gem 'stringex', '~> 1.3.0'
gem 'data_mapper', '~> 1.2.0'
gem 'sqlite3'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'rspec'
gem 'simplecov', :require => false, :group => :test
gem 'factory_girl'
